# My apps name
name: trivial-proxy

# Docker compose files that contain my apps services and tools
compose:
  - compose.yml

# Proxy settings for my services
proxy:

  # Proxy settings for the "web" service defined inside my compose.yml.
  # NOTE: You can specify more than one service.
  web:

    # By default this will proxy both port 80 and 443 giving you
    # http://trivial-proxy.lndo.site and https://trivial-proxy.lndo.site
    - trivial-proxy.lndo.site

    # You can also add any subdomains you want
    - sub.trivial-proxy.lndo.site

    # If you do not specify a domain ending in `.lndo.site` you will need
    # to add an entry in /etc/hosts
    #
    # See: https://docs.devwithlando.io/config/proxy.html#working-offline-or-using-custom-domains
    - bob.frank.kbox.com
    - frank.bob.joe
    - tippecanoe.tyler.too

    # If your service uses a different port you can add that to the end of the service
    # If your service uses both http and https use the http port
    - another.lndo.site:80
    #- andonemore.lndo.site:8000
    #- db.lndo.site:3306

    # Add a wildcard domain
    # NOTE: this needs to be encapsulated in quotes because * is a special character
    - "*.wild.trivial-proxy.lndo.site"
    - "wild.*.trivial-proxy.lndo.site"
